version : 0.2

phases:
  install :
  commands:
    - echo Installing NGINX
    - sudo apt-get install -y nginx
    - echo Starting NGINX
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html/index.html
    artifacts:
      files:
        - /var/www/html/index.html